import type {
  Exercise,
  Lesson,
  Note,
  StudentProfile,
  StudentSummary,
} from "../app/dashboard/types";

export const currentTeacherId = "t-1";

export const lessons: Lesson[] = [
  {
    id: "1",
    studentId: "st-1",
    teacherId: "t-1",
    lessonDate: "2026-01-19",
    lessonTime: "16:00 – 16:45",
    lessonType: "online",
    lessonStatus: "scheduled",
    participantName: "Alex Johnson",
    instrument: "Guitar",
  },
  {
    id: "2",
    studentId: "st-2",
    teacherId: "t-2",
    lessonDate: "2026-01-19",
    lessonTime: "18:30 – 19:15",
    lessonType: "in-person",
    lessonStatus: "completed",
    participantName: "Maria Lopez",
    instrument: "Piano",
  },
  {
    id: "4",
    studentId: "st-3",
    teacherId: "t-3",
    lessonDate: "2026-01-11",
    lessonTime: "14:00 – 14:45",
    lessonType: "hybrid",
    lessonStatus: "cancelled",
    participantName: "Daniel Kim",
    instrument: "Violin",
  },
  {
    id: "5",
    studentId: "st-4",
    teacherId: "t-4",
    lessonDate: "2026-01-23",
    lessonTime: "17:00 – 17:45",
    lessonType: "online",
    lessonStatus: "scheduled",
    participantName: "Hannah Lee",
    instrument: "Piano",
  },
];

export const exercises: Exercise[] = [
  {
    id: "ex-0",
    teacherId: "t-1",
    studentId: "st-1",
    title: "Strumming Rhythm Control",
    instrument: "Guitar",
    difficulty: "beginner",
    goal: "Practice consistent down-up strumming with a metronome at 70–90 BPM.",
    targetPerWeek: 5,
    practicedDaysThisWeek: ["Tue", "Thu", "Wed"],
  },
  {
    id: "ex-1",
    teacherId: "t-1",
    studentId: "st-1",
    title: "Basic Chord Transitions",
    instrument: "Guitar",
    difficulty: "beginner",
    goal: "Smooth G–C–D chord changes with steady tempo.",
    targetPerWeek: 3,
    practicedDaysThisWeek: ["Mon", "Sat", "Wed"],
  },
  {
    id: "ex-2",
    teacherId: "t-1",
    studentId: "st-2",
    title: "Major Scale Practice",
    instrument: "Piano",
    difficulty: "beginner",
    goal: "Play C major scale (2 octaves) evenly with metronome.",
    targetPerWeek: 5,
    practicedDaysThisWeek: ["Mon", "Wed", "Thu", "Sat"],
  },
  {
    id: "ex-3",
    teacherId: "t-1",
    studentId: "st-3",
    title: "Bowing Technique Drills",
    instrument: "Violin",
    difficulty: "intermediate",
    goal: "Straight bowing + consistent pressure on open strings.",
    targetPerWeek: 3,
    practicedDaysThisWeek: [],
  },
  {
    id: "ex-4",
    teacherId: "t-2",
    studentId: "st-2",
    title: "Rhythm Control Exercises",
    instrument: "Drums",
    difficulty: "advanced",
    goal: "Subdivisions with click (8ths/16ths) for timing control.",
    targetPerWeek: 1,
    practicedDaysThisWeek: ["Tue"],
  },
];

export const teacherLessons: Lesson[] = [
  {
    id: "t-lesson-1",
    studentId: "st-1",
    teacherId: "t-1",
    lessonDate: "2026-01-19",
    lessonTime: "16:00 – 16:45",
    lessonType: "online",
    lessonStatus: "scheduled",
    participantName: "Michael Bennett",
    instrument: "Guitar",
  },
  {
    id: "t-lesson-11",
    studentId: "st-1",
    teacherId: "t-1",
    lessonDate: "2026-01-19",
    lessonTime: "16:00 – 16:45",
    lessonType: "online",
    lessonStatus: "scheduled",
    participantName: "Michael Bennett",
    instrument: "Guitar",
  },
  {
    id: "t-lesson-2",
    studentId: "st-2",
    teacherId: "t-1",
    lessonDate: "2026-01-21",
    lessonTime: "18:30 – 19:15",
    lessonType: "in-person",
    lessonStatus: "scheduled",
    participantName: "James Rodriguez",
    instrument: "Piano",
  },
  {
    id: "t-lesson-3",
    studentId: "st-3",
    teacherId: "t-1",
    lessonDate: "2026-01-22",
    lessonTime: "14:00 – 14:45",
    lessonType: "hybrid",
    lessonStatus: "completed",
    participantName: "Sophia Nguyen",
    instrument: "Violin",
  },
  {
    id: "t-lesson-4",
    studentId: "st-4",
    teacherId: "t-1",
    lessonDate: "2026-01-3",
    lessonTime: "17:00 – 17:45",
    lessonType: "online",
    lessonStatus: "cancelled",
    participantName: "Emily Carter",
    instrument: "Piano",
  },
];

export const studentsSummaries: StudentSummary[] = [
  {
    id: "st-1",
    name: "Michael Bennett",
    instrument: "Guitar",
    lessonType: "online",
  },
  {
    id: "st-2",
    name: "James Rodriguez",
    instrument: "Piano",
    lessonType: "in-person",
  },
  {
    id: "st-3",
    name: "Sophia Nguyen",
    instrument: "Violin",
    lessonType: "in-person",
  },
  {
    id: "st-4",
    name: "Emily Carter",
    instrument: "Drums",
    lessonType: "hybrid",
  },
];

export const students: StudentProfile[] = [
  {
    id: "st-1",
    name: "Michael Bennett",
    instrument: "Guitar",
    lessonType: "online",
    email: "michael.bennet@example.com",
    location: "Kaunas, Lithuania",
    skillLevel: "Intermediate",
    bio: "Self-taught guitarist focusing on blues and rock. Looking for structured lessons to improve improvisation and timing.",
    age: 22,
  },
  {
    id: "st-2",
    name: "James Rodriguez",
    instrument: "Piano",
    lessonType: "in-person",
    email: "james.rodriguez@example.com",
    location: "Vilnius, Lithuania",
    skillLevel: "Beginner",
    bio: "Recently started learning piano and wants to build a strong foundation in reading sheet music and basic technique.",
    age: 19,
  },
  {
    id: "st-3",
    name: "Sophia Nguyen",
    instrument: "Violin",
    lessonType: "in-person",
    email: "sophia.nguyen@example.com",
    location: "Klaipėda, Lithuania",
    skillLevel: "Advanced",
    bio: "Played violin for several years. Preparing for performances and aiming to polish intonation and articulation.",
    age: 27,
  },
  {
    id: "st-4",
    name: "Emily Carter",
    instrument: "Drums",
    lessonType: "hybrid",
    email: "emily.carter@example.com",
    location: "Šiauliai, Lithuania",
    skillLevel: "Intermediate",
    bio: "Drummer with experience in band rehearsals. Wants to improve groove, fills, and independence for live gigs.",
    age: 24,
  },
];

export const notes: Note[] = [
  {
    id: "note-1",
    studentId: "st-1",
    teacherId: "t-1",
    content:
      "Great progress this week — chord transitions are smoother. Keep practicing with a metronome at 80 BPM.",
  },
  {
    id: "note-2",
    studentId: "st-1",
    teacherId: "t-1",
    content:
      "Focus on cleaner strumming patterns. Try slow down-up exercises and pay attention to even volume between strokes.",
  },
  {
    id: "note-3",
    studentId: "st-1",
    teacherId: "t-1",
    content:
      "Remember relaxed fretting hand pressure. If fingers get tired, take short breaks and repeat smaller sections.",
  },
];
